test
wogus3602/GeniePet_Server pull request #2
Opened 2020-10-26 16:44 UTC by wogus3602

2020-10-26 22:50 UTC, solone313 commented
?

2020-10-27 00:49 UTC, wogus3602 commented
test 했습니다

2020-10-27 00:52 UTC, solone313 requested changes

2020-10-27 00:52 UTC, solone313 commented on README.md
> +test
대문자로 부탁드림

2020-10-27 00:54 UTC, solone313 requested changes
굳

2020-10-27 00:54 UTC, solone313 commented on README.md
> +test
```suggestion
Test
```
대문자 ㄱ

2020-10-27 00:55 UTC, wogus3602 commented
컨펌했습니다

2020-10-27 00:56 UTC, solone313 approved these changes
굳

2020-10-27 00:57 UTC, merged